project:
  type: website
  output-dir: docs

website:
  title: "UchidaMizuki"
  favicon: logo.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/UchidaMizuki
      - text: SoundCloud
        href: https://soundcloud.com/uchidamizuki

format:
  html:
    theme: simplex

editor: visual
